services:
  go_notify:
    build: .
    container_name: go_notify_develop
    command: sh -c "uvicorn run:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    # env_file:
    #   - ../../.env
    volumes:
      - ../../:/app