services:
  api_ai:
    build: .
    container_name: api_ai_develop
    command: sh -c "uvicorn run:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    # env_file:
    #   - ../../.env
    volumes:
      - ../../:/app